chore(launcher): use patches instead of custom file
Previous `autofirma.bash` script is no longer needed as its functions
have been replaced by the `.deb` launcher and the `postinst` script
with some modifications.

diff --git a/patches/adapt-launcher.patch b/patches/adapt-launcher.patch
--- a/patches/adapt-launcher.patch
+++ b/patches/adapt-launcher.patch
@@ -1,7 +1,17 @@
 diff --git a/afirma-simple-installer/linux/instalador_deb/src/usr/bin/autofirma b/afirma-simple-installer/linux/instalador_deb/src/usr/bin/autofirma
-index 95f46ed9a..fc4e034da 100755
+index 95f46ed9a..66a28119a 100755
 --- a/afirma-simple-installer/linux/instalador_deb/src/usr/bin/autofirma
 +++ b/afirma-simple-installer/linux/instalador_deb/src/usr/bin/autofirma
-@@ -2 +2 @@
+@@ -1,2 +1,11 @@
+ #!/bin/bash
 -java -Djdk.tls.maxHandshakeMessageSize=65536 -jar /usr/lib/Autofirma/autofirma.jar "$@"
++_autofirma_dir="${HOME}/.afirma/Autofirma"
++
++if [ ! -r "${_autofirma_dir}/Autofirma_ROOT.cer" ] || [ ! -r "${_autofirma_dir}/autofirma.pfx" ]; then
++  mkdir -p "${_autofirma_dir}"
++  /app/lib/postinst || echo "WARNING: Certificate initialization failed, the application may not work correctly."
++fi
++
++unset _autofirma_dir
++
 +java -Djdk.tls.maxHandshakeMessageSize=65536 -jar /app/lib/autofirma.jar "$@"
