try and use localhost loopback as quick workaround for ELECTRON_MIRROR

diff --git a/me.anirudhsevugan.SimpliPlay.yml b/me.anirudhsevugan.SimpliPlay.yml
--- a/me.anirudhsevugan.SimpliPlay.yml
+++ b/me.anirudhsevugan.SimpliPlay.yml
@@ -33,6 +33,9 @@ modules:
       - chmod -R +x simpliplay/node_modules/
       - chmod -R +x simpliplay/node_modules/.bin/
 
+      # create fake server to fool ELECTRON_MIRROR into grabbing from there - will be removed in the future
+      - node -e "const fs = require('fs'), http = require('http'); http.createServer((req, res) => { const path = './electron-mirror' + req.url; if (fs.existsSync(path)) { res.writeHead(200); fs.createReadStream(path).pipe(res); } else { res.writeHead(404); res.end(); } }).listen(8080)" &
+      
       - |
         sed -i 's/"electron": "\^40.0.0"/"electron": "40.0.0"/g' simpliplay/package.json
 
@@ -40,10 +43,9 @@ modules:
         ROOT_DIR="$(pwd)"
         MIRROR_PATH="$ROOT_DIR/electron-mirror"
         
-        export ELECTRON_MIRROR="file://$MIRROR_PATH/"
+        export ELECTRON_MIRROR="http://127.0.0.1:8080/"
         export ELECTRON_CUSTOM_DIR="v40.0.0"
         export ELECTRON_SKIP_BINARY_DOWNLOAD=1
-        export ELECTRON_OFFLINE=1
         export XDG_CACHE_HOME="$ROOT_DIR/.cache"
         
         cd simpliplay
@@ -56,6 +58,8 @@ modules:
           --offline \
           --no-prune \
           --download.mode=off
+          
+      - kill %1 || true # clean up node server
 
       - mkdir -p /app/lib/SimpliPlay
       - cp -r simpliplay/dist/SimpliPlay-linux-x64/* /app/lib/SimpliPlay/
