Add back the Wayland perms, use them when USE_WAYLAND is 1

diff --git a/minerals/startarmcord b/minerals/startarmcord
--- a/minerals/startarmcord
+++ b/minerals/startarmcord
@@ -1,11 +1,19 @@
 #!/usr/bin/env sh
 
-FLAGS='--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer --enable-features=WaylandWindowDecorations'
+FLAGS='--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer'
 
 if [[ $XDG_SESSION_TYPE =~ "[Ww]ayland" ]] && [ -c /dev/nvidia0 ]
 then
     FLAGS="$FLAGS --disable-gpu-sandbox"
 fi
 
+declare -i USE_WAYLAND="${USE_WAYLAND:-0}"
+declare -i EXIT_CODE=0
+
+if [[ "${USE_WAYLAND}" -eq 1 && "${XDG_SESSION_TYPE}" == "wayland" ]]; then
+    zypak-wrapper /app/bin/armcord/armcord $FLAGS --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland $@ || EXIT_CODE=$?
+    # Fall back to x11 if failed to launch under Wayland. Otherwise, exit normally
+    [[ "${EXIT_CODE}" -ne 133 ]] && exit "${EXIT_CODE}"
+fi
 
 env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-xyz.armcord.xyz}" zypak-wrapper /app/bin/armcord/armcord $FLAGS "$@"
